name: pymc_env
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.13
  - pymc
  - pymc-marketing
  - arviz
  - numpy
  - scipy
  - pandas
  - xarray
  - statsmodels
  - jax
  - jaxlib
  - numpyro
  - blackjax
  - nutpie
  - jupyterlab
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - tqdm
  - pip
  - pip:
      - pymc-extras
      - pymc-experimental
