name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pymc>=5
  - pymc-marketing
  - arviz
  - numpy
  - scipy
  - pandas
  - xarray
  - statsmodels
  - jax>=0.4,<0.5
  - jaxlib>=0.4,<0.5
  - numpyro
  - blackjax
  - nutpie
  - jupyterlab
  - ipykernel
  - ipywidgets
  - widgetsnbextension
  - tqdm
  - pip
  - pip:
      - "pymc-extras @ git+https://github.com/pymc-devs/pymc-extras.git"
      - "pymc-experimental @ git+https://github.com/pymc-devs/pymc_experimental.git"
